#if !canImport(ObjectiveC)
import XCTest

extension VotingBoothTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VotingBoothTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(VotingBoothTests.__allTests__VotingBoothTests),
    ]
}
#endif
