#if !canImport(ObjectiveC)
import XCTest

extension StringExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringExtensionsTests = [
        ("testInvalidEmails", testInvalidEmails),
        ("testValidEmails", testValidEmails),
    ]
}

extension UserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserTests = [
        ("testEmptyUser", testEmptyUser),
        ("testHashingFunction", testHashingFunction),
        ("testMatchingPasswords", testMatchingPasswords),
        ("testNamedEmptyUser", testNamedEmptyUser),
        ("testNonMatchingPasswords", testNonMatchingPasswords),
        ("testSalt", testSalt),
        ("testUsernameValidity", testUsernameValidity),
        ("testUsernameValidityEmptyUser", testUsernameValidityEmptyUser),
        ("testVerifyNonMatchingPassword", testVerifyNonMatchingPassword),
        ("testVerifyPassword", testVerifyPassword),
    ]
}

extension VotingBoothTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VotingBoothTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(StringExtensionsTests.__allTests__StringExtensionsTests),
        testCase(UserTests.__allTests__UserTests),
        testCase(VotingBoothTests.__allTests__VotingBoothTests),
    ]
}
#endif
